name: Reusable - Test Coverage

on:
  workflow_call:
    outputs:
      coverage-dir:
        description: 'Coverage directory path'
        value: './coverage'

jobs:
  test-coverage:
    uses: ./.github/workflows/reusable/npm-ci.yml

  run-tests:
    needs: test-coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: node_modules

      - uses: actions/cache@v4
        with:
          path: .vitest
          key: vitest-${{ runner.os }}-${{ hashFiles('**/*.ts') }}

      - run: npm run test:coverage

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./coverage
