name: On GitHub Release

on:
  release:
    types: [published]

jobs:
  install:
    uses: ./.github/workflows/npm-ci.yml

  publish:
    uses: ./.github/workflows/publish-npm.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
