name: Upload Codecov

on:
  workflow_call:
    inputs:
      clover-path:
        required: true
        type: string
      fail_ci_if_error:
        required: false
        type: boolean
        default: true
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Checkout Repository
        uses: actions/checkout@v4

      - name: 📂 Download Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: 📊 Submit to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ inputs.clover-path }}
          fail_ci_if_error: ${{ inputs.fail_ci_if_error }}